language: php

php:
  - 5.4

branches:
  only:
    - 7.x-1.x
    - travis

mysql:
  database: drupal
  username: root
  encoding: utf8

install:
  - sudo apt-get update > /dev/null
  - "mysql -e 'create database drupal;'"

  - pear channel-discover pear.drush.org
  - pear install drush/drush-6.1.0.0
  - phpenv rehash

  # Build Behat dependencies
  - cd ./tests/behat
  - composer install
  # - cp behat.template.yml behat.local.yml
  - cd ../../../

  # Build Codebase
  - mkdir private_files
  - mkdir profiles
  - mv panopoly profiles/
  - mkdir drupal
  - mv profiles drupal/

  # Test the current branch
  - cd drupal
  - drush make --prepare-install profiles/panopoly/build-panopoly-dev.make --yes
  # - cp profiles/panopoly/settings.php.example sites/default/settings.php
  # - cp profiles/panopoly/settings.local.php.example sites/default/settings.local.php
  - cd ../

  # Setup files
  - sudo chmod -R 777 drupal/sites/all

  # Setup display for Selenium
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - sleep 5

  # Get Selenium
  - wget http://selenium.googlecode.com/files/selenium-server-standalone-2.37.0.jar
  - java -jar selenium-server-standalone-2.37.0.jar > /dev/null 2>&1 &
  - sleep 5

before_script:

  - cd drupal
  - php -d sendmail_path=`which true` `pear config-get php_dir`/drush/drush.php si panopoly --db-url=mysql://root:@127.0.0.1/drupal --account-name=admin --account-pass=admin --site-mail=admin@example.com --site-name="Panopoly" --yes
  - drush runserver --server=builtin 8888 > /dev/null 2>&1 &
  - sleep 3
  - cd profiles/panopoly/tests/behat

script:

  - ./bin/behat --config behat.travis.yml
